### ISSUE TITLE
Please use BSD license so code can be used in other software

### ISSUE THREAD

**Issue by mdejong** [salviati/cuckoo#1]
Releasing this Go library under the GPL means that it cannot be used in any software other than GPLed software. For a standalone program or application, that would be fine. But, to publish library code that cannot realistically be used makes no sense. Please apply the BSD 2 clause license instead.

**Comment by salviati** [comment]
> Releasing this Go library under the GPL means that it cannot be used in any software other than GPLed software.

That is the point. You can see [this page](https://www.gnu.org/philosophy/why-not-lgpl.html) for the reasoning behind this choice.

**Comment by criloz** [comment]
@salviati have you mind changed in the last year?
